import { readFile, mkdir } from 'node:fs/promises';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
import { RailEngine } from '../src/rail-engine.js';
const require = createRequire(import.meta.url), { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const origin = process.env.TEST_ORIGIN || 'http://localhost:4175';
const packet = JSON.parse(await readFile(new URL('../data/rail-journeys.json', import.meta.url), 'utf8'));
const engine = new RailEngine(); engine.setNetwork(JSON.parse(await readFile(new URL('../data/rail-network.json', import.meta.url), 'utf8'))); engine.setJourneys(packet.journeys, packet.delays.entities);
const train = engine.positions().find(i => i.journey.geometry && !i.atStation && i.ratio > .1 && i.ratio < .8);
assert.ok(train, 'A currently running scheduled train is required for the real-data movement check');
const browser = await chromium.launch({ channel: 'msedge', headless: true, args: ['--enable-webgl', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
await mkdir(new URL('../artifacts/', import.meta.url), { recursive: true });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 } }); page.setDefaultTimeout(40000);
  const errors = [], responses = [];
  // A read-only hook exists only in this intercepted test response, never in the published app.
  await page.route('**/src/app.js*', async route => {
    const source = await readFile(new URL('../src/app.js', import.meta.url), 'utf8');
    await route.fulfill({ contentType: 'text/javascript', body: source + '\nwindow.__atlasQA = () => ({ viewer, routeView, selected, packets, errors, items });' });
  });
  page.on('pageerror', e => { errors.push(e.message); console.log('Page error:', e.message); });
  page.on('console', message => { if (message.type() === 'error' && !message.text().includes('status of 404')) console.log('Browser console:', message.text().slice(0,350)); });
  page.on('response', r => { if (/digitraffic|amtraker|overpass/.test(r.url())) responses.push({ url: r.url(), status: r.status() }); });
  await page.route('**/api/status', r => r.fulfill({ status: 404, body: '{}' }));
  await page.route('**/nominatim.openstreetmap.org/**', r => r.fulfill({ contentType: 'application/json', body: '[]' }));
  await page.goto(origin); await page.waitForFunction(() => document.getElementById('loading').hidden);
  await page.waitForTimeout(4000);
  const search = async query => { await page.locator('[data-panel="search"]').click(); await page.locator('#query').fill(query); await page.locator('#query').press('Enter'); await page.locator('[data-result-vehicle]').first().click(); };
  console.log('Train:', train.name, train.trip);
  await search(train.trip); await page.waitForSelector('#detail:not([hidden])');
  assert.ok((await page.locator('#detail').textContent()).includes('estimada por horario'));
  assert.ok(await page.locator('.journey-stops li').count() > 1);
  assert.ok(await page.evaluate(() => window.__atlasQA().routeView.lines.length > 0), 'Selecting a train must draw its route');
  const coords = () => page.locator('.vehicle-data>div').last().textContent();
  const before = await coords(); await page.waitForTimeout(4500); assert.notEqual(await coords(), before, 'A running timetable estimate must move on the map clock');
  await page.screenshot({ path: 'artifacts/v03-train-route.png' });
  await page.locator('#follow-vehicle').click(); assert.equal(await page.locator('#follow-vehicle').getAttribute('aria-pressed'), 'true');
  await page.waitForTimeout(1500); await page.locator('#follow-vehicle').click();
  console.log('Scheduled movement, stops, route and follow verified.');
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(500);
  const mobile = await page.locator('#detail').boundingBox(); assert.ok(mobile.x >= 0 && mobile.x + mobile.width <= 390);
  await page.screenshot({ path: 'artifacts/v03-mobile-route.png' }); await page.setViewportSize({ width: 1440, height: 960 });
  await page.locator('#detail-close').click();
  await search('ISS (ZARYA)');
  await page.waitForTimeout(6000);
  console.log('Satellite state:', await page.locator('#state-space').textContent(), 'detail visible:', await page.locator('#detail').isVisible(), 'notice:', await page.locator('#notice').textContent());
  assert.equal(await page.locator('#detail').isVisible(), true);
  const orbital = await coords(); await page.waitForTimeout(3000); assert.notEqual(await coords(), orbital);
  console.log('Orbit drawing:', await page.evaluate(() => { const q = window.__atlasQA(); return { points: q.routeView.orbit?.points.length, id: q.routeView.orbit?.id, selected: q.selected?.id, entities: q.routeView.entities.length }; }));
  assert.ok(await page.evaluate(() => window.__atlasQA().routeView.lines.length > 0), 'The selected orbital route must be drawn');
  await page.screenshot({ path: 'artifacts/v03-orbit-route.png' });
  await page.evaluate(() => { const q = window.__atlasQA(); q.viewer.camera.setView({ destination: Cesium.Cartesian3.fromDegrees(q.selected.lon, q.selected.lat, 19000000) }); q.viewer.scene.requestRender(); });
  await page.waitForTimeout(2000); await page.screenshot({ path: 'artifacts/v03-orbit-world.png' });
  console.log('International requests:', JSON.stringify(responses));
  await page.waitForFunction(() => window.__atlasQA().packets.fi && window.__atlasQA().packets.na);
  const countries = await page.evaluate(() => [...new Set(window.__atlasQA().items.rail.map(i => i.country || i.source))]);
  for (const country of ['España', 'Francia', 'Finlandia', 'Estados Unidos', 'Canadá']) assert.ok(countries.includes(country), 'Missing rail coverage: ' + country);
  assert.deepEqual(errors, []);
} finally { await browser.close(); }
