import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true, args: ['--enable-webgl', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const origin = process.env.TEST_ORIGIN || 'http://localhost:4173';
await mkdir(new URL('../artifacts/', import.meta.url), { recursive: true });
const errors = [];
const capture = (page, name) => page.screenshot({ path: fileURLToPath(new URL(`../artifacts/${name}.png`, import.meta.url)) });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
  page.on('pageerror', e => errors.push(e.message));
  await page.goto(origin);
  await page.waitForSelector('#loading.done', { timeout: 30000 });
  await page.waitForFunction(() => document.getElementById('air-total').textContent !== '—');
  await page.waitForTimeout(3500);
  await capture(page, 'desktop');
  await page.locator('.toolbar [data-panel="filters"]').click();
  await page.locator('[data-filter="rail"]').uncheck();
  assert.equal(await page.locator('#rail-total').textContent(), '0');
  await page.locator('[data-filter="rail"]').check();
  assert.notEqual(await page.locator('#rail-total').textContent(), '0');
  await page.locator('#dimension').click();
  await page.waitForFunction(() => document.getElementById('dimension').textContent === '3D' && !document.getElementById('dimension').disabled);
  assert.equal(await page.locator('[data-filter="rail"]').isChecked(), true);
  await capture(page, 'flat');
  await page.locator('#dimension').click();
  await page.waitForFunction(() => document.getElementById('dimension').textContent === '2D' && !document.getElementById('dimension').disabled);
  await page.locator('#filters [data-close]').click();
  const feed = await (await fetch(origin + '/api/trains')).json();
  const target = feed.items[0];
  await page.locator('.toolbar [data-panel="search"]').click();
  await page.locator('#query').fill(target.code);
  await page.locator('#query').press('Enter');
  await page.locator('.result').first().click();
  await page.waitForSelector('#detail:not([hidden])');
  assert.ok((await page.locator('#detail').textContent()).includes('Renfe'));
  await page.waitForTimeout(2000);
  await capture(page, 'train');
  await page.locator('#close-detail').click();
  await page.locator('.toolbar [data-panel="layers"]').click();
  await page.locator('[data-base="night"]').click();
  assert.equal(await page.locator('[data-base="night"]').getAttribute('aria-pressed'), 'true');
  await page.locator('[data-base="natural"]').click();
  await page.locator('#layers [data-close]').click();
  await page.locator('#zoom').click();
  await page.waitForFunction(() => document.getElementById('zoom').textContent === '100%', { timeout: 20000 });
  await page.setViewportSize({ width: 390, height: 844 });
  await page.waitForTimeout(1200);
  await capture(page, 'mobile');
  await page.locator('.toolbar [data-panel="filters"]').click();
  const bounds = await page.locator('#filters').boundingBox();
  assert.ok(bounds.x >= 0 && bounds.x + bounds.width <= 390);
  await capture(page, 'mobile-filters');
  const staticPage = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  staticPage.on('pageerror', e => errors.push(e.message));
  await staticPage.route('**/api/status', r => r.fulfill({ status: 404, body: '{}' }));
  await staticPage.goto(origin);
  await staticPage.waitForFunction(() => document.getElementById('connection').textContent.includes('Instantáneas'));
  assert.notEqual(await staticPage.locator('#rail-total').textContent(), '0');
  await staticPage.locator('.toolbar [data-panel="about"]').click();
  assert.ok((await staticPage.locator('#mode-note').textContent()).includes('Modo de instantáneas'));
  assert.deepEqual(errors, []);
  console.log('Browser QA passed: 2D/3D, filters, search/details, layers, reset, mobile, snapshots. No page errors.');
} finally { await browser.close(); }
