import { mkdir } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { createRequire } from 'node:module';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true, args: ['--enable-webgl', '--use-angle=swiftshader', '--enable-unsafe-swiftshader'] });
const origin = process.env.TEST_ORIGIN || 'http://localhost:4174';
await mkdir(new URL('../artifacts/', import.meta.url), { recursive: true });
const errors = [], capture = (page, name) => page.screenshot({ path: fileURLToPath(new URL(`../artifacts/${name}.png`, import.meta.url)) });
try {
  const page = await browser.newPage({ viewport: { width: 1440, height: 960 } });
  page.setDefaultTimeout(60000);
  page.on('pageerror', e => { errors.push(e.message); console.log('Page error:', e.message); });
  await page.route('**/api/status', r => r.fulfill({ status: 404, body: '{}' }));
  await page.route('**/nominatim.openstreetmap.org/**', r => r.fulfill({ contentType: 'application/json', body: JSON.stringify([{ lat: '35.681', lon: '139.767', name: 'Tokio', display_name: 'Tokio, Japón', type: 'city' }]) }));
  await page.goto(origin);
  await page.waitForFunction(() => document.getElementById('loading').hidden);
  await page.waitForFunction(() => document.getElementById('connection').textContent.includes('Aviación: instantáneas'));
  await page.waitForTimeout(5000);
  assert.equal(await page.locator('.brand,.world-caption,.swatch,#air-total,#rail-total').count(), 0);
  assert.equal(await page.locator('.toolbar button').last().getAttribute('id'), 'zoom');
  assert.equal((await page.locator('.toolbar').textContent()).trim(), '100%');
  await capture(page, 'v04-world');
  console.log('World symbols and toolbar verified.');
  await page.locator('[data-panel="layers"]').click();
  assert.equal(await page.locator('[data-base]').count(), 8);
  assert.equal(await page.locator('#layers input').count(), 1);
  await page.locator('#base-labels').check();
  await page.locator('#base-labels').uncheck();
  await page.locator('[data-base="bathymetry"]').click();
  await page.waitForTimeout(1500);
  assert.equal(await page.locator('[data-base="bathymetry"]').getAttribute('aria-pressed'), 'true');
  await page.locator('[data-base="satellite"]').click();
  await page.waitForTimeout(1500);
  await page.locator('#layers [data-close]').click();
  await page.locator('#about-button').click();
  const about = await page.locator('#about').boundingBox();
  assert.ok(Math.abs(about.x + about.width / 2 - 720) < 2);
  assert.ok((await page.locator('#about').textContent()).includes('Versión 0.4.0'));
  assert.equal(await page.locator('#about a[href$="/Portfolio/"]').count(), 1);
  await capture(page, 'v04-about');
  await page.locator('#about-close').click();
  console.log('Layers and About verified.');
  await page.locator('#legend-toggle').click(); assert.equal(await page.locator('#legend').isVisible(), true);
  await page.locator('#legend-close').click(); assert.equal(await page.locator('#legend').isVisible(), false);
  await page.locator('[data-panel="filters"]').click();
  await page.locator('summary').filter({hasText: 'Trenes'}).click();
  assert.equal(await page.locator('#rail-opacity').inputValue(), '1');
  assert.equal(await page.locator('#station-opacity').inputValue(), '1');
  assert.equal(await page.locator('#rail-options').evaluate(e => e.closest('details').querySelector('summary').textContent), 'Trenes');
  await page.locator('[data-filter="air"]').uncheck(); await page.locator('[data-filter="air"]').check();
  await page.locator('[data-color="airHeavy"]').evaluate(e => { e.value = '#ff3366'; e.dispatchEvent(new Event('input', { bubbles: true })); });
  assert.ok((await page.evaluate(() => localStorage.getItem('transportination.preferences'))).includes('#ff3366'));
  await page.locator('summary').filter({ hasText: 'Presentación' }).click();
  await page.locator('#reset-colors').click();
  await page.locator('#filters [data-close]').click();
  await page.locator('[data-panel="search"]').click();
  await page.locator('#query').fill('Tokio'); await page.locator('#query').press('Enter');
  await page.locator('[data-result-place]').first().click();
  await page.waitForFunction(() => document.getElementById('coordinates').textContent === '35.68° · 139.77°' && document.getElementById('zoom').textContent === '27.143%');
  const zoom = await page.locator('#zoom').textContent(), coords = await page.locator('#coordinates').textContent();
  await page.locator('#dimension').click(); await page.waitForFunction(() => !document.getElementById('dimension').disabled);
  assert.equal(await page.locator('#dimension').getAttribute('aria-label'), 'Cambiar a 3D');
  assert.equal(await page.locator('#coordinates').textContent(), coords);
  assert.equal(await page.locator('#zoom').textContent(), zoom);
  console.log('Local view preserved in 2D/3D.');
  await capture(page, 'v04-flat');
  await page.locator('#dimension').click(); await page.waitForFunction(() => !document.getElementById('dimension').disabled);
  assert.equal(await page.locator('#coordinates').textContent(), coords);
  assert.equal(await page.locator('#zoom').textContent(), zoom);
  await page.locator('[data-panel="search"]').click();
  await page.locator('#query').fill('ISS (ZARYA)'); await page.locator('#query').press('Enter');
  await page.locator('[data-result-vehicle]').first().click();
  await page.waitForSelector('#detail:not([hidden])');
  assert.ok((await page.locator('#detail').textContent()).includes('SGP4'));
  const before = await page.locator('#detail .vehicle-data').textContent();
  await page.waitForTimeout(4500);
  const after = await page.locator('#detail .vehicle-data').textContent();
  assert.notEqual(after, before, 'Orbital coordinates must move with real time');
  await capture(page, 'v04-satellite');
  await page.locator('#detail-close').click();
  await page.locator('#zoom').click(); await page.waitForTimeout(1800);
  await page.setViewportSize({ width: 390, height: 844 }); await page.waitForTimeout(1000);
  const toolbar = await page.locator('.toolbar').boundingBox();
  assert.ok(toolbar.x >= 0 && toolbar.x + toolbar.width <= 390);
  await capture(page, 'v04-mobile');
  await page.locator('[data-panel="filters"]').click();
  const filters = await page.locator('#filters').boundingBox(); assert.ok(filters.x >= 0 && filters.x + filters.width <= 390);
  await capture(page, 'v04-mobile-filters');
  assert.deepEqual(errors, []);
  console.log('Browser QA passed: worldwide view, icon-only toolbar, vertical layers, centered About, colors, legend, world search, preserved 2D/3D view, moving SGP4 satellites and mobile. No page errors.');
} finally { await browser.close(); }
